### ISSUE TITLE
assert statement in sub-sampling of normals for training contains multiple typos

### ISSUE THREAD

**Issue by stephan-hutter** [smshuai/U1-snRNA#2]
I am using a PON with 100+ samples, so the sub-sampling for training takes effect. This, however, doesn't work. I get this error message:

> AssertionError: <30 useful normal samples for positive strand

It looks like `assert` in lines 122-123 of beta_binomial_model.py is wrongly implemented:

`assert keep_p.shape[0] < 30, "<30 useful normal samples for positive strand"`
`assert keep_p.shape[0] < 30, "<30 useful normal samples for negative strand"`

`<`should be `>=` here.

Also, in line 123 `assert keep_p.shape[0]` probably should be `assert keep_n.shape[0]`

**Comment by smshuai** [comment]
Hi Stephan,

Thanks for pointing this out! I add these assertions at the last min to provide some controls for others...apparently, I did the opposite. I will modify it now!

Best,
Shimin
