### ISSUE TITLE
pysam package version 

### ISSUE THREAD

**Issue by Gray-Tu** [smshuai/U1-snRNA#3]
Hi smshuai,

I tried to run the mutation_call/analyze_multi_map.sh, but I get an error of pysam:
```
Traceback (most recent call last):
  File ".//bam2fq_for_realign.py", line 27, in <module>
    fq = pysam.fastq('-O', bam_tmp).split('\n')
AttributeError: module 'pysam' has no attribute 'fastq'
```
My python is 3.6.8 and the pysam version is 0.8.3.
Could you tell me the version of pysam you used ?

**Comment by smshuai** [comment]
Hi Gary,

I think you need to upgrade the pysam. For example, version "0.15.3" has the function. Since this function is the same as `samtools fastq`, you may also need a compatible `htslib` library.

Best,
Shimin

**Comment by Gray-Tu** [comment]
Hi smshuai,
It work after updating the pysam package.
Thank you for your rapid response.
